name: tyamo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  rounded_loading_button: ^2.1.0
  circular_profile_avatar: ^2.0.5
  getwidget: ^3.1.1
  page_transition: ^2.0.9
  responsive_sizer: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/